// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	WatchCreateRequest
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_READ      Type = 0
	Type_WRITE     Type = 1
	Type_READWRITE Type = 2
)

var Type_name = map[int32]string{
	0: "READ",
	1: "WRITE",
	2: "READWRITE",
}
var Type_value = map[string]int32{
	"READ":      0,
	"WRITE":     1,
	"READWRITE": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WatchCreateRequest struct {
	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type Type   `protobuf:"varint,2,opt,name=type,enum=main.Type" json:"type,omitempty"`
}

func (m *WatchCreateRequest) Reset()                    { *m = WatchCreateRequest{} }
func (m *WatchCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchCreateRequest) ProtoMessage()               {}
func (*WatchCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*WatchCreateRequest)(nil), "main.WatchCreateRequest")
	proto.RegisterEnum("main.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72, 0xe3, 0x12, 0x0a,
	0x4f, 0x2c, 0x49, 0xce, 0x70, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02,
	0x31, 0x85, 0xe4, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c,
	0xb8, 0xf4, 0x40, 0x9a, 0xf5, 0x42, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0xe2, 0x5a, 0x5a, 0x5c, 0x2c,
	0x20, 0x9e, 0x10, 0x07, 0x17, 0x4b, 0x90, 0xab, 0xa3, 0x8b, 0x00, 0x83, 0x10, 0x27, 0x17, 0x6b,
	0x78, 0x90, 0x67, 0x88, 0xab, 0x00, 0xa3, 0x10, 0x2f, 0x17, 0x27, 0x48, 0x10, 0xc2, 0x65, 0x4a,
	0x62, 0x03, 0x3b, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x59, 0xc1, 0x4b, 0x74, 0x8d, 0x00,
	0x00, 0x00,
}
