// Code generated by protoc-gen-go.
// source: datapb.proto
// DO NOT EDIT!

/*
Package datapb is a generated protocol buffer package.

datapb.proto

It is generated from these files:
	datapb.proto

It has these top-level messages:
	SampleData
*/
package datapb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}

type SampleData struct {
	Label            *string                   `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32                    `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps             []int64                   `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *SampleData_OptionalGroup `protobuf:"group,4,opt,name=OptionalGroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SampleData) Reset()         { *m = SampleData{} }
func (m *SampleData) String() string { return proto.CompactTextString(m) }
func (*SampleData) ProtoMessage()    {}

const Default_SampleData_Type int32 = 77

func (m *SampleData) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *SampleData) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_SampleData_Type
}

func (m *SampleData) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *SampleData) GetOptionalgroup() *SampleData_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type SampleData_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SampleData_OptionalGroup) Reset()         { *m = SampleData_OptionalGroup{} }
func (m *SampleData_OptionalGroup) String() string { return proto.CompactTextString(m) }
func (*SampleData_OptionalGroup) ProtoMessage()    {}

func (m *SampleData_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

func init() {
	proto.RegisterEnum("datapb.FOO", FOO_name, FOO_value)
}
